project:
  type: website
  output-dir: docs

website:
  title: "2025 V4SDB Student Winter School"
  sidebar:
    style: "docked"
    search: true  
    contents:
      - text: "Introduction"
        href: index.qmd
   
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true