project:
  type: website
  output-dir: docs

website:
  title: "2025 V4SDB Student Winter School"
  sidebar:
    style: "docked"
    logo: "images/2025V4SDBWinterSchool_logo.png"
    title: "2025 V4SDB Student Winter School Materials" 
    pinned: true
    search: true
    page-footer: "Copyright 2025, Máté Varga"  
    contents:
      - text: "Introduction (EN)"
        href: index.qmd
      - text: "Bevezető (HU)"
        href: bevezeto.qmd  
      - text: "Programme (EN)"
        href: programme.qmd
      - text: "Program (HU)"
        href: program_hu.qmd  
      - text: "OpenScience Lecture"
        href: open_science.qmd
      - section: "Tutorials"
        contents: 
           - text: "Cell Tracking"
             href: cell_tracking.qmd
           - text: "Bonsai"
             href: bonsai.qmd
           - text: "Connectome Analysis"
             href: connectome.qmd
           - text: "Calcium Imaging"
             href: calcium_imaging.qmd
           - text: "Lightsheet Data"
             href: lightsheet_data.qmd
      - text: "Gallery"
        href: gallery.qmd
 
   
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true