---
title: "Introduction to Bonsai"
---

Materials for the  V4SDB Student Winter School Bonsai introduction and tutorial 

31.01.2025 - 11:30 - 13:00

**Instructor:**

Adriana Nagy-Dăbâcan (Transylvanian Institute of Neuroscience)<br> 
dabacan@tins.ro

## Workshop Overview

During the session, we will present Bonsai as a reactive programming tool usefull when designing and analyzing behavioral experiments. We will go through the potential applications for Bonsai and its most relevant usecases. 
Then, we will get familiar with this tool by implementing a simple workflow combining animal tracking with closed loop control. We will showcase basic programming principles and will open the door for addressing more complex needs in experimental design.

By the end of the workshop, participants will be familiar with Bonsai as a tool for behavioral experimental control and will understand its basic principles of operation. They will have a good source of documentation and will be able to join the community for further support. 

[slides (to be updated)]()

## Software
[**Bonsai**](https://bonsai-rx.org/docs/articles/installation.html): 

-  An open-source visual reactive programming software for interactive systems.
-  built to work with .NET framework in Windows 7 or later.
-  for Linux installation, see pointers [here](https://github.com/orgs/bonsai-rx/discussions/1101).

## Prepare the field

- Download and install [Bonsai](https://bonsai-rx.org/docs/articles/installation.html).
- Install the Starter Pack from the Package Manager.
- Check out the Bonsai Gallery and make sure the example workflows work on your station.
- Download the [video file](https://github.com/dabacana/V4SDB_Bonsai_Intro/blob/main/mouse_arena.avi) for this workshop. 

## Workshop step-by-step

1. Open and visualize video file.
2. Detect animal using simple image processing functions.
3. Compute centroid coordinates in arena.
4. Implement simple conditionals using Logical operators.
5. Integrate python scripting for more complex logics.
6. Trigger some digital line/speaker when animal leaves predetermined home area.

## Bonsai Resources

- [Documentation](https://bonsai-rx.org/docs/)
- [Github Forum](https://github.com/orgs/bonsai-rx/discussions)
- [Public Discord Server](https://discord.com/invite/QcthRPuZnr)
- [Learning Resources](https://bonsai-rx.org/learn/)

## References
Lopes, G., Bonacchi, N., Frazão, J., Neto, J. P., Atallah, B. V., Soares, S., ... & Kampff, A. R. (2015). **Bonsai: an event-based framework for processing and controlling data streams.** *Frontiers in Neuroinformatics**, 9, 7. [https://doi.org/10.3389/fninf.2015.00007](https://doi.org/10.3389/fninf.2015.00007)