---
title: "2025 V4SDB Winter School Programme"
---

## Preliminary programme {.unnumbered}

### Tuesday, January 28

| Time          | Activity                                    |
|:--------------|:--------------------------------------------|
| 13:00-14:00   | Registration                                |
| 14:00-15:00   | **"Open Science in (In)Action: Why, What, and How"**<br> Public Lecture by Gáspár Jékely     |
| 15:00-16:00   | Coffee Break, Registration                  |
| 16:00-17:30   | Flash Talks by Students                     |
| 20:00-23:00   | Social Program  (at [The Grund](https://maps.app.goo.gl/FUw6Qk3jtZvpqaRZ9))                           |

### Wednesday, January 29

| Time          | Activity                                    |
|:--------------|:--------------------------------------------|
| 09:00-11:00   | [Morning Session I (Gáspár Jékely)](connectome.qmd)          |
| 11:00-11:30   | Coffee Break                               |
| 11:30-13:00   | [Morning Session II (Gáspár Jékely)](connectome.qmd)         |
| 13:00-14:30   | Lunch (buffet)                             |
| 14:30-16:30   | [Afternoon Session I (Joanna Pylvänäinen)](cell_tracking.qmd)   |
| 16:30-17:00   | Coffee Break                               |
| 17:00-18:30   | [Afternoon Session II (Joanna Pylvänäinen)](cell_tracking.qmd)  |

### Thursday, January 30

| Time          | Activity                                    |
|:--------------|:--------------------------------------------|
| 09:00-11:00   | [Morning Session I (Isaac Bianco)](calcium_imaging.qmd)           |
| 11:00-11:30   | Coffee Break                               |
| 11:30-13:00   | [Morning Session II (Isaac Bianco)](calcium_imaging.qmd)          |
| 13:00-14:30   | Lunch (buffet)                             |
| 14:30-16:30   | [Afternoon Session I (Kenzo Ivanovitch)](lightsheet_data.qmd)     |
| 16:30-17:00   | Coffee Break                               |
| 17:00-18:30   | [Afternoon Session II (Kenzo Ivanovitch)](lightsheet_data.qmd)    |

### Friday, January 31

| Time          | Activity                                    |
|:--------------|:--------------------------------------------|
| 09:00-11:00   | ~~Morning Session I (Giulia Bertolin - online)~~ (Cancelled) |
| 11:00-11:30   | Coffee Break                               |
| 11:30-13:00   | [Morning Session II (Adriana Nagy-Dăbâcan)](bonsai.qmd)       |
| 13:00-13:30   | Closing remarks, Lunch (take away)         |

::: {.callout-note}
## Programme notes
- All sessions include breaks to maintain engagement and provide networking opportunities
- A social program is scheduled for the first evening at [The Grund](https://maps.app.goo.gl/7v89dYzURw8ySDSm9)
- One session will be conducted online (Giulia Bertolin's session on Thursday morning)
:::


## Location {.unnumbered}

The Winter School will take place on the premises of the Faculty of Science of ELTE Eötvös Loránd University - Pázmány Péter stny. 1/A, 1117 Budapest. Lectures will be in room 0.83 ("Eötvös terem") - follow the signs.

```{=html}
<center>
<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2791.5959249048856!2d19.059148411877455!3d47.474579896964826!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4741ddaaf46cfc7d%3A0x3621cb6fd0c8825d!2zQnVkYXBlc3QsIFDDoXptw6FueSBQw6l0ZXIgc3RueS4gMS9BLCAxMTE3!5e1!3m2!1sen!2shu!4v1737054930007!5m2!1sen!2shu" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
</center>
```